version: '3.8'
services:
  postgres:
    image: postgres:15
    container_name: postgres_container
    environment:
      POSTGRES_DB: demo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 45454545
    ports:
      - "5433:5432"

  springboot_app:
    image: springjdbc
    container_name: springboot_container
    build: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: 45454545
    ports:
      - "8000:8080"
    depends_on:
      - postgres
