spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/demo?currentSchema=myschema
    username: postgres
    password: 45454545
    driver-class-name: org.postgresql.Driver
  config:
    import: classpath:application-queries.yml
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect


